# A quick database environment setup with a postgres database and pgadmin web client

# Docker compose file version
version: "3.5"

# The containers part of this setup
services:
  # The postgres Database service running on port 5432
  postgreSQL-database:
    image: "postgres:alpine"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  # The http based pgadmin client for postgres database accessed at http://localhost:5050
  pgadmin-management-console:
    image: "dpage/pgadmin4:latest"
    restart: "always"
    ports:
      - "5050:80"
    depends_on:
      - "postgreSQL-database"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
